# Generated by Django 5.1.5 on 2025-02-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teza_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='capitalized_words_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='words_followed_by_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
