# Generated by Django 5.1.5 on 2025-02-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teza_app', '0002_submission_capitalized_words_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='capitalized_words_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='words_followed_by_numbers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
