import openai
import requests
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import F
from openai import OpenAI
import os
from asgiref.sync import sync_to_async
from .models import Submission
from django.http import JsonResponse
from asgiref.sync import sync_to_async
from .models import Submission  # Import your model
from asgiref.sync import sync_to_async
from .models import Submission
from google import genai
from google.genai import types

import openai
from asgiref.sync import sync_to_async
from .models import Submission
from google import genai
import aiohttp
import asyncio

async def call_gemini_api(prompt, api_key):
    """
    Sends an asynchronous request to the Gemini API and returns the response.

    :param prompt: The text input for the model.
    :param api_key: Your API key for authenticating with the Gemini API.
    :return: The generated response from the Gemini API.
    """
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"
    headers = {
        "Content-Type": "application/json"
    }
    params = {
        "key": api_key
    }
    data = {
        "contents": [
            {
                "parts": [{"text": prompt}]
            }
        ]
    }

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers, params=params, json=data) as response:
                response.raise_for_status()  # Raise exception for HTTP errors
                response_data = await response.json()  # Parse JSON response asynchronously
                return response_data  # Return the entire JSON response
    except aiohttp.ClientError as e:
        print(f"Gemini API Error: {e}")
        return {"error": str(e)}



# Hardcoded OpenAI API Key (Replace with your actual key)
OPENAI_API_KEY = ''
import json
import requests
from asgiref.sync import sync_to_async
from .models import Submission

# Hardcoded OpenAI API Key (Replace with your actual key)

async def generate_content(request):
    if request.method == "POST":
        name = request.POST.get("name")
        band = request.POST.get("band")
        year = int(request.POST.get("year"))
        gemini_api_key = request.POST.get("api_key")  # Gemini API key for text generation

        # Determine if the year is even or odd
        is_even = year % 2 == 0

        # Step 1: **Generate Text using Gemini** (Keeping Original Logic)
        text_prompt = f"Describe what happened in {year} for {band} and why someone likes them."
        api_response = await call_gemini_api(text_prompt, gemini_api_key)

        if "error" in api_response:
            generated_text = "An error occurred while generating content."
        else:
            try:
                generated_text = api_response["candidates"][0]["content"]["parts"][0]["text"]
            except (KeyError, IndexError):
                generated_text = "No content was generated by the Gemini API."

        # Step 2: **Generate Image using OpenAI's DALL·E**
        image_prompt = f"A photo of {band} performing live in {year}, studio lighting, dramatic stage, longshot."
        image_url = await generate_dalle_image(image_prompt)

        # Step 3: **Save the submission to the database**
        submission = await sync_to_async(Submission.objects.create)(
            name=name,
            band=band,
            year=year,
            generated_text=generated_text,
            generated_image_url=image_url
        )

        # Step 4: **Return JSON Response**
        return JsonResponse({
            "name": submission.name,
            "band": submission.band,
            "year": submission.year,
            "is_even": is_even,
            "generated_text": submission.generated_text,
            "generated_image_url": submission.generated_image_url
        })

import aiohttp

async def generate_dalle_image(prompt):
    """
    Calls OpenAI's DALL·E API asynchronously using aiohttp to generate an image.
    """
    url = "https://api.openai.com/v1/images/generations"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {OPENAI_API_KEY}"
    }
    payload = {
        "prompt": prompt,
        "n": 1,
        "size": "1024x1024"
    }

    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers, json=payload) as response:
                if response.status == 200:
                    data = await response.json()
                    return data["data"][0]["url"]
                else:
                    print(f"DALL·E Error: {response.status}, {await response.text()}")
                    return ""
    except Exception as e:
        print(f"Error generating DALL·E image: {e}")
        return ""


def index(request):
    last_submission = Submission.objects.last()  # Get the latest submission
    if last_submission:
        year_parity = "Even" if last_submission.is_year_even() else "Odd"
    else:
        year_parity = None

    # Add the years range to the context
    years = range(1960, 2026)

    return render(request, "teza_app/index.html", {
        "last_submission": last_submission,
        "year_parity": year_parity,
        "years": years  # Pass the years to the template
    })